version: '3'
services:
  proxy:
    container_name: proxy-blake
    restart: always
    build: proxy-blake
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
